import type { Metadata } from "next";
import {
  neueHassGroteskLight,
  neueHassGroteskRoman,
  neueHassGroteskMedium,
  inter,
  futura,
} from "@/fonts";

import "./globals.css";

import Navbar from "@/components/common/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  
                ${inter.variable} ${neueHassGroteskLight.variable} 
                ${neueHassGroteskRoman.variable} ${neueHassGroteskMedium.variable}
                ${futura.variable}
              `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
