import type { Metadata } from "next";
import {
  neueHassGroteskLight,
  neueHassGroteskRoman,
  neueHassGroteskMedium,
  inter,
  futura,
} from "@/fonts";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import "./globals.css";

import Navbar from "@/components/common/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`  
                ${inter.variable} ${neueHassGroteskLight.variable} 
                ${neueHassGroteskRoman.variable} ${neueHassGroteskMedium.variable}
                ${futura.variable}
              `}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
